
apply plugin: 'java-library'

sourceSets {
    main {
        java.srcDirs = ["src"]
        resources.srcDirs = ["res"]
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://www.jitpack.io' }
}

ext {
    copperVersion = '0.1.0'
    // fetch this field from https://github.com/MDTCopper/loader/blob/<copperVersion>/gradle.properties
    // replace <copperVersion> to the value of copperVersion variable above
    mixinVersion = '0.1.3'
    gameVersion = 'v159.7'
}

dependencies {
    // if your mod depends on some other mods, add this:
    // compileOnly files('path/to/your/dependency/mod.jar')

    compileOnly "com.github.MDTCopper.loader:core:$copperVersion"
    compileOnly "com.github.MDTCopper.loader:mod:$copperVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$gameVersion"
    annotationProcessor "com.github.MDTCopper:Mixin:$mixinVersion:processor"
}

jar {
    dependsOn configurations.runtimeClasspath
    from ({
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }) {
        include '*'
    }
    from (projectDir) {
        include  'copper.mod.json', 'copper.mod.hjson'
    }
    duplicatesStrategy = DuplicatesStrategy.WARN
}
