
apply plugin: 'java-library'

sourceSets {
    main {
        java.srcDirs = ["src"]
        resources.srcDirs = ["res"]
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://www.jitpack.io' }
}

ext {
    // use a release tag or a commit hash
    // do not use `snapshot`. it's for github release
    // do not use `-SNAPSHOT`. it'll stuck for a long time because jitpack rebuild it everytime you fetch
    copperVersion = '71ac7d5899'
    // fetch this field from https://github.com/MDTCopper/loader/blob/<copperVersion>/gradle.properties
    // replace <copperVersion> to the value of copperVersion variable above
    mixinVersion = '0.1.3'
    gameVersion = 'v159.7'
}

configurations {
    loaderDesktop { transitive = false }
}

dependencies {
    // if your mod depends on some other mods, add this:
    // compileOnly files('path/to/your/dependency/mod.jar')

    compileOnly "com.github.MDTCopper.loader:core:$copperVersion"
    compileOnly "com.github.MDTCopper.loader:mod:$copperVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$gameVersion"
    annotationProcessor "com.github.MDTCopper:Mixin:$mixinVersion:processor"

    // for mod debugging
    loaderDesktop "com.github.MDTCopper.loader:desktop:$copperVersion"
}

jar {
    dependsOn configurations.runtimeClasspath
    from ({
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }) {
        include '*'
    }
    from (projectDir) {
        include 'copper.mod.json', 'copper.mod.hjson'
        include 'icon.png'
    }
    duplicatesStrategy = DuplicatesStrategy.WARN
}

tasks.register('downloadLoader') {
    def targetFile = layout.projectDirectory.file('loader.jar')
    outputs.file(targetFile)

    onlyIf { !targetFile.asFile.exists() }

    doLast {
        def target = targetFile.asFile
        if (target.exists())
            return

        def desktopJar = configurations.loaderDesktop.resolve().find {
            it.name.endsWith('.jar') && it.name.contains('desktop')
        }
        if (desktopJar == null) {
            throw new GradleException(
                    "failed to parse loader: $copperVersion"
            )
        }

        target.parentFile?.mkdirs()
        target.bytes = desktopJar.bytes
        logger.lifecycle("downloaded loader: $copperVersion")
    }
}

tasks.register('downloadMindustry') {
    def targetFile = layout.projectDirectory.file('game.jar')
    def downloadUrl = "https://github.com/Anuken/Mindustry/releases/download/${gameVersion}/Mindustry.jar"
    outputs.file(targetFile)

    onlyIf { !targetFile.asFile.exists() }

    doLast {
        def target = targetFile.asFile
        target.parentFile?.mkdirs()
        logger.lifecycle("downloading Mindustry from ${downloadUrl} ...")
        new URL(downloadUrl).withInputStream { input ->
            target.withOutputStream { output ->
                output << input
            }
        }
        logger.lifecycle("downloaded Mindustry: $gameVersion")
    }
}

tasks.register('prepareDebugJar', Copy) {
    dependsOn jar
    from jar
    into layout.projectDirectory.dir('.mindustry/copper/mods')
    rename { 'mod-to-debug.jar' }
}

tasks.register('prepareDebug') {
    group = 'build'
    dependsOn 'downloadLoader'
    dependsOn 'downloadMindustry'
    dependsOn 'prepareDebugJar'
}
